# Configuración de GitHub-MD-Book
defaults:
  workspace: .
  cover: true
  toc: true
  encoding: utf-8
  directory: output
  basename: book
  types:
    - HTML
    - PDF

builds:
  - workspace: .
    basename: libro
